export const CREATE_SALON_REQUEST = 'CREATE_SALON_REQUEST';
export const CREATE_SALON_SUCCESS = 'CREATE_SALON_SUCCESS';
export const CREATE_SALON_FAILURE = 'CREATE_SALON_FAILURE';

export const FETCH_SALONS_REQUEST = 'FETCH_SALONS_REQUEST';
export const FETCH_SALONS_SUCCESS = 'FETCH_SALONS_SUCCESS';
export const FETCH_SALONS_FAILURE = 'FETCH_SALONS_FAILURE';

export const FETCH_SALON_BY_ID_REQUEST = 'FETCH_SALON_BY_ID_REQUEST';
export const FETCH_SALON_BY_ID_SUCCESS = 'FETCH_SALON_BY_ID_SUCCESS';
export const FETCH_SALON_BY_ID_FAILURE = 'FETCH_SALON_BY_ID_FAILURE';

export const SEARCH_SALONS_REQUEST = 'SEARCH_SALONS_REQUEST';
export const SEARCH_SALONS_SUCCESS = 'SEARCH_SALONS_SUCCESS';
export const SEARCH_SALONS_FAILURE = 'SEARCH_SALONS_FAILURE';
